import fs from 'fs';


const returnSkillsList = () => {
    const tempSkillsList = [
        "hadoop",
        "spark",
        "mapreduce",
        "data lakes",
        "data warehousing",
        "big data architecture",
        "nosql",
        "data modeling",
        "etl",
        "cloud computing",
        "aws",
        "azure",
        "data governance",
        "security",
        "ansible",
        "linux",
        "automation",
        "cloud platforms",
        "ci/cd",
        "infrastructure as code",
        "kubernetes",
        "docker",
        "terraform",
        "python",
        "scripting",
        "networking",
        "artifactory",
        "jenkins",
        "maven",
        "gradle",
        "build automation",
        "version control",
        "git",
        "jfrog cli",
        "ai strategy",
        "machine learning",
        "team management",
        "project management",
        "data science",
        "deep learning",
        "communication",
        "budgeting",
        "stakeholder management",
        "innovation",
        "mentoring",
        "ai architecture",
        "system design",
        "scalability",
        "model deployment",
        "machine learning",
        "research methods",
        "tensorflow",
        "pytorch",
        "data analysis",
        "statistical analysis",
        "algorithm design",
        "scientific writing",
        "kafka",
        "sql",
        "java",
        "scala",
        "data pipelines",
        "data visualization",
        "data mining",
        "ci/cd",
        "build tools",
        "maven",
        "ant",
        "chef",
        "ruby",
        "configuration management",
        "sql",
        "excel",
        "power bi",
        "r",
        "statistics",
        "data cleansing",
        "tableau",
        "data modeling",
        "data integration",
        "data security",
        "cloud computing",
        "google cloud",
        "ansible",
        "docker",
        "elasticsearch",
        "logstash",
        "kibana",
        "log management",
        "gerrit",
        "code review",
        "jenkins",
        "groovy",
        "jira",
        "atlassian suite",
        "agile methodologies",
        "workflow configuration",
        "user management",
        "kubernetes",
        "python",
        "keras",
        "natural language processing",
        "computer vision",
        "algorithms",
        "linux",
        "windows server",
        "troubleshooting",
        "monitoring",
        "system administration",
        "big data architecture",
        "hadoop",
        "data analysis",
        "troubleshooting",
        "databases",
        "itil",
        "puppet",
        "leadership",
        "sre",
        "devops",
        "splunk",
        "dashboards",
        "alerting",
        ".net",
        "c#",
        "asp.net",
        "sql server",
        "web api",
        "mvc",
        "entity framework",
        "linq",
        "wcag",
        "aria",
        "accessibility testing",
        "assistive technologies",
        "html",
        "css",
        "javascript",
        "ui/ux",
        "ada compliance",
        "agile methodologies",
        "scrum",
        "kanban",
        "jira",
        "confluence",
        "android sdk",
        "kotlin",
        "ui/ux design",
        "rest apis",
        "android studio",
        "firebase",
        "mobile development",
        "appdynamics",
        "application performance monitoring",
        ".net",
        "metrics",
        "application security",
        "sast",
        "dast",
        "penetration testing",
        "vulnerability management",
        "owasp",
        "secure coding",
        "cloud security",
        "aws",
        "cloudformation",
        "cloud architecture",
        "aws lambda",
        "ec2",
        "s3",
        "azure",
        "arm templates",
        "bamboo",
        "bitbucket",
        "branching strategies",
        "blockchain",
        "ethereum",
        "smart contracts",
        "solidity",
        "cryptocurrency",
        "distributed ledger",
        "consensus algorithms",
        "web3",
        "node.js",
        "business analysis",
        "requirements gathering",
        "process improvement",
        "uml",
        "bpmn",
        "c#",
        "chef inspec",
        "compliance as code",
        "virtualization",
        "cloud architecture",
        "microservices",
        "cloud networking",
        "vpc",
        "subnets",
        "routing",
        "security groups",
        "firewalls",
        "cloud security",
        "iam",
        "identity and access management",
        "encryption",
        "gcp",
        "compliance",
        "cnc programming",
        "g-code",
        "cad/cam",
        "machining",
        "manufacturing processes",
        "blueprints",
        "toolpath optimization",
        "programming",
        "data structures",
        "problem solving",
        "debugging",
        "software development",
        "3d animation",
        "2d animation",
        "motion graphics",
        "adobe creative suite",
        "maya",
        "blender",
        "storyboarding",
        "visual effects",
        "hardware design",
        "circuit design",
        "embedded systems",
        "microprocessors",
        "pcb design",
        "testing",
        "validation",
        "network design",
        "switching",
        "lan/wan",
        "tcp/ip",
        "vpn",
        "cloud networking",
        "c++",
        "research methods",
        "publications",
        "programming",
        "system analysis",
        "confluence",
        "collaboration",
        "documentation",
        "consul",
        "service discovery",
        "coverage.py",
        "code coverage",
        "quality assurance",
        "database design",
        "er diagrams",
        "data wrangling",
        "database management",
        "mysql",
        "postgresql",
        "oracle",
        "performance tuning",
        "backup and recovery",
        "datadog",
        "devops",
        "devsecops",
        "security automation",
        "continuous security",
        "vulnerability scanning",
        "team management",
        "containerization",
        "embedded c",
        "rtos",
        "microcontrollers",
        "firmware development",
        "hardware design",
        "communication protocols",
        "javascript",
        "networking",
        "html",
        "web development fundamentals",
        "ui/ux basics",
        "envoy",
        "service mesh",
        "traffic management",
        "falco",
        "threat detection",
        "system monitoring",
        "fluentd",
        "data collection",
        "data processing",
        "elasticsearch",
        "fortify",
        "static code analysis",
        "react",
        "angular",
        "vue.js",
        "spring framework",
        "django",
        "framework development",
        "react",
        "typescript",
        "sass",
        "express.js",
        "mongodb",
        "java",
        "hibernate",
        "j2ee",
        "junit",
        "flask",
        "unity",
        "game design",
        "game engines",
        "vr development",
        "unreal engine",
        "google cloud",
        "git",
        "github",
        "github actions",
        "gitlab",
        "gitlab ci",
        "gradle",
        "grafana",
        "groovy",
        "information architecture",
        "user research",
        "wireframing",
        "prototyping",
        "content strategy",
        "security",
        "network security",
        "ids/ips",
        "security auditing",
        "interaction design",
        "usability testing",
        "swift",
        "objective-c",
        "ios sdk",
        "xcode",
        "istio",
        "project management",
        "team leadership",
        "it infrastructure",
        "cybersecurity",
        "jacoco",
        "junit",
        "unit testing",
        "test automation",
        "dependency management",
        "microservices",
        "api design",
        "soa",
        "ios",
        "swift",
        "react native",
        "flutter",
        "mulesoft",
        "anypoint platform",
        "api development",
        "integration",
        "nagios",
        "tcp/ip",
        "cisco",
        "networking protocols",
        "new relic",
        "nexus",
        "artifact repository",
        "nomad",
        "container orchestration",
        "notary",
        "container security",
        "cryptography",
        "trust management",
        "octopus deploy",
        "deployment automation",
        "powershell",
        "openshift",
        "openstack",
        "oracle",
        "pl/sql",
        "oracle sql developer",
        "database development",
        "packer",
        "php",
        "laravel",
        "restful apis",
        "symfony",
        "powershell",
        "active directory",
        "product management",
        "roadmap planning",
        "prometheus",
        "pytest",
        "automation testing",
        "selenium",
        "testng",
        "agile testing",
        "performance testing",
        "redux",
        "robotics",
        "ros",
        "control systems",
        "sensors",
        "actuators",
        "ruby on rails",
        "salesforce",
        "apex",
        "visualforce",
        "lightning",
        "soql",
        "salesforce administration",
        "seo",
        "keyword research",
        "on-page optimization",
        "off-page optimization",
        "content marketing",
        "analytics",
        "selenium",
        "webdriver",
        "testing frameworks",
        "sharepoint",
        "sharepoint framework",
        "software design",
        "sonarqube",
        "code quality",
        "splunk enterprise security",
        "security information and event management (siem)",
        "incident response",
        "security analysis",
        "t-sql",
        "ssrs",
        "ssis",
        "incident management",
        "linux administration",
        "windows server administration",
        "systems design",
        "linux administration",
        "teamcity",
        "technical sales",
        "product knowledge",
        "customer engagement",
        "networking technologies",
        "account management",
        "technical support",
        "customer relationship management (crm)",
        "team leadership",
        "software development lifecycle (sdlc)",
        "terraform",
        "infrastructure as code (iac)",
        "tfs (team foundation server)",
        ".net development tools",
        ".net framework",
        "udeploy (urbancode deploy)",
        "deployment strategies",
        "ui design principles",
        "figma",
        "user testing",
        "html5",
        "css3",
        "jquery",
        "responsive design",
        "angularjs",
        "reactjs",
        "unity3d engine",
        "game development principles",
        "3d modeling",
        "animation",
        "user experience design principles",
        "interaction design",
        "hashicorp vault",
        "secrets management",
        "access control",
        "ui/ux design",
        "php",
        "wordpress",
        "html5",
        "xl deploy",
        "zabbix",
        "monitoring tools",
        "alerting systems",
        "network monitoring"
    ]
    const uniqueSkillsList = [...new Set(tempSkillsList.map(skill => skill.toLowerCase()))]
    return uniqueSkillsList.sort((a, b) => a.localeCompare(b));
}

const returnTitlesList = () => {
    const tempTitlesList = fs.readFileSync('./job-titles_list.json', 'utf8');
    return JSON.parse(tempTitlesList);
}

const logStatements = (string, err = null) => {
    if (err !== null)
        console.log(`Error ocurred: `, err);

    console.log(string);
}


export {
    logStatements,
    returnSkillsList,
    returnTitlesList
}